export {About} from './about'
export {Experience} from './experience'
export {Education} from './education'
export {Skills} from './skills'
export {Interest} from './interest'
export {Award} from './award'